# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Leo/Desktop/FPGA/HW6/HW6.srcs/sources_1/bd/hw6/ip/hw6_matrix_cal_0_0/hw6_matrix_cal_0_0.xci
# IP: The module: 'hw6_matrix_cal_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leo/Desktop/FPGA/HW6/HW6.srcs/sources_1/bd/hw6/ip/hw6_matrix_cal_0_0/src/ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw6_matrix_cal_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Leo/Desktop/FPGA/HW6/HW6.srcs/sources_1/bd/hw6/ip/hw6_matrix_cal_0_0/hw6_matrix_cal_0_0.xci
# IP: The module: 'hw6_matrix_cal_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leo/Desktop/FPGA/HW6/HW6.srcs/sources_1/bd/hw6/ip/hw6_matrix_cal_0_0/src/ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw6_matrix_cal_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
