# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ricky/Desktop/Xilinx-designtool/project/Lab6/Lab6.srcs/sources_1/bd/design_1/ip/design_1_matrix_processor_ctrl_0_1/design_1_matrix_processor_ctrl_0_1.xci
# IP: The module: 'design_1_matrix_processor_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ricky/Desktop/Xilinx-designtool/project/Lab6/Lab6.srcs/sources_1/bd/constrs_1/imports/bram_control_2.0/bram_control_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_matrix_processor_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ricky/Desktop/Xilinx-designtool/project/Lab6/Lab6.srcs/sources_1/bd/design_1/ip/design_1_matrix_processor_ctrl_0_1/design_1_matrix_processor_ctrl_0_1.xci
# IP: The module: 'design_1_matrix_processor_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ricky/Desktop/Xilinx-designtool/project/Lab6/Lab6.srcs/sources_1/bd/constrs_1/imports/bram_control_2.0/bram_control_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_matrix_processor_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
