# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/FFT_system/FFT_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_system || ORIG_REF_NAME==FFT_system} -quiet] -quiet

# IP: bd/FFT_system/ip/FFT_system_processing_system7_0_0/FFT_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_system_processing_system7_0_0 || ORIG_REF_NAME==FFT_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/FFT_system/ip/FFT_system_FFT_0_0/FFT_system_FFT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_system_FFT_0_0 || ORIG_REF_NAME==FFT_system_FFT_0_0} -quiet] -quiet

# IP: bd/FFT_system/ip/FFT_system_ps7_0_axi_periph_0/FFT_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==FFT_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FFT_system/ip/FFT_system_rst_ps7_0_100M_0/FFT_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==FFT_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/FFT_system/ip/FFT_system_auto_pc_0/FFT_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_system_auto_pc_0 || ORIG_REF_NAME==FFT_system_auto_pc_0} -quiet] -quiet

# XDC: bd/FFT_system/FFT_system_ooc.xdc
