# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw6/hw6.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw6 || ORIG_REF_NAME==hw6} -quiet] -quiet

# IP: bd/hw6/ip/hw6_matrix_cal_0_0/hw6_matrix_cal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw6_matrix_cal_0_0 || ORIG_REF_NAME==hw6_matrix_cal_0_0} -quiet] -quiet

# IP: bd/hw6/ip/hw6_processing_system7_0_0/hw6_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw6_processing_system7_0_0 || ORIG_REF_NAME==hw6_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw6/ip/hw6_ps7_0_axi_periph_0/hw6_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw6_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw6_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw6/ip/hw6_rst_ps7_0_100M_0/hw6_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw6_rst_ps7_0_100M_0 || ORIG_REF_NAME==hw6_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/hw6/ip/hw6_auto_pc_0/hw6_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw6_auto_pc_0 || ORIG_REF_NAME==hw6_auto_pc_0} -quiet] -quiet

# XDC: bd/hw6/hw6_ooc.xdc
